settings:
  recovery:
    index: true       # print files indexing
    events: false     # print each event
    tools: false      # print each tool
  legacy:
    force: false      # enable polling watcher
    interval: 0s      # polling interval
server:
  status: false       # web panel
  open: true          # open in default browser
  port: 3000          # server port
  host: localhost     # server host
schema:
- name: realize       # project name
  path: .             # project path, '.' is for wdir path
  commands:           # all go commands supported
    generate:         # go generate
      status: true
    install:          # go install
      status: true
    vet:              # go vet
      status: true
    test:             # go test
      status: true
    fmt:              # go fmt
      status: true
  watcher:
    paths:            # paths watched
    - /
    extensions:       # extensions watched
    - go
    - html
    - css
    - js
    ignored_paths:    # paths ignored
    - .git
    - .realize
    - .idea
    - vendor
    - realize/assets
    - realize/bindata.go
